### ISSUE TITLE
请问大佬，如何改成青龙运行？

### ISSUE THREAD

**Issue by xiaoqi2020** [wes-lin/Cloud189Checkin#12]
请问大佬，如何改成青龙运行？

**Comment by wes-lin** [comment]
青龙面板我没具体用过，不过看了相关的文档，在青龙上运行和本地运行差不多，你只要把你的账号密码设置在环境变量里就行了。如果你尝试不行话，我后面自己装个青龙实验下，再完善下说明文档。

**Comment by xiaoqi2020** [comment]
> 青龙面板我没具体用过，不过看了相关的文档，在青龙上运行和本地运行差不多，你只要把你的账号密码设置在环境变量里就行了。如果你尝试不行话，我后面自己装个青龙实验下，再完善下说明文档。

老板，我一直在等你的青龙运行教程哦！

**Comment by xiaoqi2020** [comment]
> 青龙面板我没具体用过，不过看了相关的文档，在青龙上运行和本地运行差不多，你只要把你的账号密码设置在环境变量里就行了。如果你尝试不行话，我后面自己装个青龙实验下，再完善下说明文档。

我把脚本fork到了青龙运行出现以下错误
## 开始执行... 2023-08-29 10:50:24


node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'superagent'
Require stack:
- /ql/data/scripts/cloud189/src/app.swap.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/ql/data/scripts/cloud189/src/app.swap.js:21:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/cloud189/src/app.swap.js' ]
}


Node.js v18.16.0



## 执行结束... 2023-08-29 10:50:26  耗时 2 秒

**Comment by xiaoqi2020** [comment]
安装superagent模块后 又出现以下错误

## 开始执行... 2023-08-29 10:53:31



node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '../telegramBot'
Require stack:
- /ql/data/scripts/cloud189/src/app.swap.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/ql/data/scripts/cloud189/src/app.swap.js:25:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/cloud189/src/app.swap.js' ]
}

Node.js v18.16.0



## 执行结束... 2023-08-29 10:53:34  耗时 3 秒

**Comment by xiaoqi2020** [comment]
最新进展

## 开始执行... 2023-08-29 10:55:45


[32m[2023-08-29T10:55:47.611] [INFO] default - [39m账户 189****2804开始执行

[32m[2023-08-29T10:55:52.867] [INFO] default - [39m已经签到过了，签到获得90M空间

[32m[2023-08-29T10:55:52.869] [INFO] default - [39m第2次抽奖失败,次数不足
[32m[2023-08-29T10:55:52.869] [INFO] default - [39m第3次抽奖失败,次数不足



## 执行结束... 2023-08-29 10:55:52  耗时 7 秒　　　

这样子应该是运行成功了吧？

**Comment by wes-lin** [comment]
是的，这样log就是成功了的。

**Comment by wes-lin** [comment]
> > 青龙面板我没具体用过，不过看了相关的文档，在青龙上运行和本地运行差不多，你只要把你的账号密码设置在环境变量里就行了。如果你尝试不行话，我后面自己装个青龙实验下，再完善下说明文档。
> 
> 老板，我一直在等你的青龙运行教程哦！

最近比较忙，一直没时间更新。不过不知道你是为了安全考虑还是别的因素。其实我觉得用github action每天定时运行已经能满足目前的需求了。自己弄台服务器来搞青龙跑这个脚本是不是有点大材小用了。

**Comment by xiaoqi2020** [comment]
> > > 青龙面板我没具体用过，不过看了相关的文档，在青龙上运行和本地运行差不多，你只要把你的账号密码设置在环境变量里就行了。如果你尝试不行话，我后面自己装个青龙实验下，再完善下说明文档。
> > 
> > 
> > 老板，我一直在等你的青龙运行教程哦！
> 
> 最近比较忙，一直没时间更新。不过不知道你是为了安全考虑还是别的因素。其实我觉得用github action每天定时运行已经能满足目前的需求了。自己弄台服务器来搞青龙跑这个脚本是不是有点大材小用了。

github自动炮一段时间就停了，又要手动去运行一下
青龙我是搭建在路由器的

**Comment by wes-lin** [comment]
确实有这个问题，好像是半年就需要自己重新点一次。不过其实也还好，有消息推送，可以知道什么时候停了，随便改个文件就又能继续半年了。

**Comment by Aijiaobin** [comment]
> > 青龙面板我没具体用过，不过看了相关的文档，在青龙上运行和本地运行差不多，你只要把你的账号密码设置在环境变量里就行了。如果你尝试不行话，我后面自己装个青龙实验下，再完善下说明文档。
> 
> 老板，我一直在等你的青龙运行教程哦！

如果要青龙上运行，把地址添加到订阅里面，然后手动添加 src/app.js 到定时任务。就可以了。如果日志提示缺少一来就到依赖里面添加一下。就可以了。我的已经跑起来了。

**Comment by Fengikjing** [comment]
![Image](https://github.com/user-attachments/assets/202e83fb-c8b7-4f04-94b2-4ea31a7d34cb)
