### ISSUE TITLE
8月6日更新后不能用了

### ISSUE THREAD

**Issue by thesexday** [wes-lin/Cloud189Checkin#67]
设置好了多账号，但是没法正常签到啊。

**Comment by thesexday** [comment]
> cloud@1.0.0 start
> node --env-file=.env --unhandled-rejections=strict ./src/app.js
[2024-08-07T14:29:36.308] [INFO] default - 账户 189****5863开始执行
(node:1818) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: 024-08-07T14:29:37.698] [ERROR] default - RequestError
    at ClientRequest.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:[12](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:13)8:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1116:18)
    at internalConnectMultiple (node:net:1184:5)
    at internalConnectMultiple (node:net:1184:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:5[14](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:15):7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1723040976352,
    socket: 1723040976354,
    lookup: 1723040976945,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1723040977697,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 591,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 1345
    }
  }
}
[2024-08-07T14:29:37.699] [INFO] default - 账户 189****5863执行完毕
[2024-08-07T14:29:37.699] [INFO] default - 账户 189****7998开始执行
Error: 024-08-07T14:29:38.454] [ERROR] default - RequestError
    at ClientRequest.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:[16](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:17)9:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1116:18)
    at internalConnectMultiple (node:net:1184:5)
    at internalConnectMultiple (node:net:1184:5)
    at Timeout.internalConnectMultipleTimeout (node:net:[17](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:18)10:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1723040977701,
    socket: 1723040977701,
    lookup: 1723040977702,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1723040978453,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 752
    }
  }
}
[2024-08-07T14:29:38.454] [INFO] default - 账户 [18](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:19)9****7998执行完毕
[2024-08-07T14:29:38.454] [INFO] default - 账户 198****0328开始执行
Error: 024-08-07T14:29:39.210] [ERROR] default - RequestError
    at ClientRequest.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:5[19](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:20):28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1116:18)
    at internalConnectMultiple (node:net:1184:5)
    at internalConnectMultiple (node:net:1184:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1723040978456,
    socket: 1723040978457,
    lookup: 1723040978457,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1723040979210,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 754
    }
  }
}
[[20](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:21)24-08-07T14:29:39.210] [INFO] default - 账户 198****0328执行完毕
[2024-08-07T14:29:39.[21](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:22)1] [INFO] default - 账户 189****3675开始执行
Error: 024-08-07T14:29:39.967] [ERROR] default - RequestError
    at ClientRequest.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1116:18)
    at internalConnectMultiple (node:net:1184:5)
    at internalConnectMultiple (node:net:1184:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 17[23](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:24)040979213,
    socket: 1723040979213,
    lookup: 1723040979213,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1723040979966,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 753
    }
  }
}
[20[24](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:25)-08-07T14:29:39.967] [INFO] default - 账户 189****3675执行完毕
Command completed after 1 attempt(s).

**Comment by thesexday** [comment]
> cloud@1.0.0 start
> node --env-file=.env --unhandled-rejections=strict ./src/app.js
[2024-08-07T14:29:36.308] [INFO] default - 账户 189####5863开始执行
(node:1818) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: 024-08-07T14:29:37.698] [ERROR] default - RequestError
    at ClientRequest.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:[12](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:13)8:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1116:18)
    at internalConnectMultiple (node:net:1184:5)
    at internalConnectMultiple (node:net:1184:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1710:5)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:5[14](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:15):7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1723040976352,
    socket: 1723040976354,
    lookup: 1723040976945,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: [17](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:18)23040977697,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 591,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 1345
    }
  }
}
[2024-08-07T14:29:37.699] [INFO] default - 账户 [18](https://github.com/thesexday/Cloud189Checkin/actions/runs/10286286512/job/28466571554#step:6:19)9####5863执行完毕

**Comment by wes-lin** [comment]
明天check下

**Comment by wes-lin** [comment]
再更新看看,改了依赖版本,我这边是一直成功的

**Comment by thesexday** [comment]
今天同步了一次，可以用了。

**Comment by wes-lin** [comment]
降低了node版本,请再sync,会比较稳定些
