### ISSUE TITLE
多帐号签到错误

### ISSUE THREAD

**Issue by StarUI** [wes-lin/Cloud189Checkin#71]
多帐号签到运行错误

![image](https://github.com/user-attachments/assets/a6150053-82ff-4758-bc21-a9c87fb7e687)

SyntaxError: Unterminated string in JSON at position 94
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/accounts.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/src/app.js:24:18)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)

疑似密码里有#号，更改密码后，还是出错，代码为:

SyntaxError: Expected ',' or ']' after array element in JSON at position 51
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/accounts.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:[19](https://github.com/StarUI/Cloud189Checkin/actions/runs/10330783940/job/28600236862#step:6:20))
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/src/app.js:24:18)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)

**Comment by wes-lin** [comment]
不太像，看错误好像是你的密码里有'字符，你可以先找个json在线检验的测下你的配置字符串对不对

**Comment by StarUI** [comment]
更改完后,还是错误
Error: 024-08-11T09:17:43.562] [ERROR] default - RequestError
    at ClientRequest.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/home/runner/work/Cloud189Checkin/Cloud189Checkin/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:[16](https://github.com/StarUI/Cloud189Checkin/actions/runs/10338620741/job/28616961890#step:6:17)9:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1118:18)
    at internalConnectMultiple (node:net:1186:5)
    at internalConnectMultiple (node:net:1186:5)
    at Timeout.internalConnectMultipleTimeout (node:net:[17](https://github.com/StarUI/Cloud189Checkin/actions/runs/10338620741/job/28616961890#step:6:18)12:5)
    at listOnTimeout (node:internal/timers:583:11)
    at process.processTimers (node:internal/timers:5[19](https://github.com/StarUI/Cloud189Checkin/actions/runs/10338620741/job/28616961890#step:6:20):7) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1723367862245,
    socket: 1723367862246,
    lookup: 1723367862809,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1723367863561,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 563,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 1316
    }
  }
}

**Comment by thesexday** [comment]
还是老脚本稳，新脚本一直不行。配置说明不详细，也不知道问题出在哪里。是不是因为密码中间有特殊字符。

**Comment by wes-lin** [comment]
已经降低node版本,重新sync下
