### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by lywly** [wes-lin/Cloud189Checkin#76]
> 求助

JSON校验过了，没问题，不知道为什么一直报这个错误。
密码在`Re6`后面还有的，这是识别不全吗？是不是因为密码里有字符吗？比如密码里含有`#%&@`之类的。
```
> cloud@1.0.0 start
> node --unhandled-rejections=strict ./src/app.js

undefined:1
[{"userName":"xxxxx","password":"Re6

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/accounts.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:[12](https://github.com/lywly/Cloud189Checkin/actions/runs/10389498844/job/28767643955#step:6:13)03:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/Cloud189Checkin/Cloud189Checkin/src/app.js:25:18)
    at Module._compile (node:internal/modules/cjs/loader:[13](https://github.com/lywly/Cloud189Checkin/actions/runs/10389498844/job/28767643955#step:6:14)64:[14](https://github.com/lywly/Cloud189Checkin/actions/runs/10389498844/job/28767643955#step:6:15))

Node.js v18.20.4
Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
```

**Comment by wes-lin** [comment]
方便提供下密码中特殊字符串吗？

**Comment by wes-lin** [comment]
更新了readme 说明,请查看下修改变量,加上单引号''

**Comment by lywly** [comment]
按照新的readme说明，加上单引号''已解决。
